<?php

/*
|--------------------------------------------------------------------------
| AI Website Builder (Growth Engine)
|--------------------------------------------------------------------------
| Sites are generated by Claude in queued jobs: one call for the design system
| (stylesheet, header, footer), then one call per page. Timing invariants:
|   request_timeout < job_timeout < queue retry_after (queue.connections.site-builder)
*/

return [

    // Anthropic API key (Console → API keys). Falls back to the SDK's own credential lookup.
    'api_key' => env('ANTHROPIC_API_KEY'),

    'model' => env('SITE_BUILDER_MODEL', 'claude-opus-5'),

    // Output ceiling per call. Thinking counts toward it, so leave headroom above the
    // largest page body.
    'max_tokens' => (int) env('SITE_BUILDER_MAX_TOKENS', 32000),

    // Seconds for one API request (the SDK retries 429/5xx itself, twice).
    'request_timeout' => (float) env('SITE_BUILDER_REQUEST_TIMEOUT', 900),

    // Seconds a job may run before the worker kills it.
    'job_timeout' => (int) env('SITE_BUILDER_JOB_TIMEOUT', 960),

    'queue' => [
        'connection' => env('SITE_BUILDER_QUEUE_CONNECTION', 'site-builder'),
        'name' => env('SITE_BUILDER_QUEUE', 'site-builder'),
        // Whether `schedule:run` starts a worker for this queue every minute.
        'scheduler_starts_worker' => (bool) env('SITE_BUILDER_SCHEDULER_STARTS_WORKER', true),
    ],

    // Files: uploaded logos live on this disk.
    'disk' => env('SITE_BUILDER_DISK', 'local'),

    'max_pages' => (int) env('SITE_BUILDER_MAX_PAGES', 12),

    // Brand tone presets offered on the form (free-text notes refine them).
    'tones' => [
        'warm' => 'Warm & reassuring',
        'professional' => 'Professional & clinical',
        'friendly' => 'Friendly & casual',
        'premium' => 'Premium & refined',
        'energetic' => 'Energetic & modern',
    ],

    // schema.org type for the LocalBusiness structured data on every page.
    'business_types' => [
        'Dentist' => 'Dental practice',
        'MedicalBusiness' => 'Medical practice',
        'LocalBusiness' => 'Other local business',
    ],

    // Starting page list for a new site.
    'default_pages' => [
        ['title' => 'Home', 'path' => '/', 'notes' => ''],
        ['title' => 'About Us', 'path' => '/about/', 'notes' => ''],
        ['title' => 'Services', 'path' => '/services/', 'notes' => ''],
        ['title' => 'Contact', 'path' => '/contact/', 'notes' => ''],
    ],
];
